SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[schedules](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[schedule_name] [varchar](20) NOT NULL,
	[check_in_time] [varchar](8) NOT NULL,
	[check_out_time] [varchar](8) NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[schedules] ADD  CONSTRAINT [PK_schedule] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
